server:
  address: localhost
  port: 8008
  servlet:
    context-path: /ticapi
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sws
    password: sws
  liquibase:
    change-log: classpath:/db/master-changelog.xml
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
