server:
  address: localhost
  port: 8008
  servlet:
    context-path: /ticapi
spring:
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  liquibase:
    change-log: classpath:/db/master-changelog.xml
  jpa:
    database:
      platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: validate
